import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import { cookies } from 'next/headers'
import axios from 'axios'

import '@/sass/index.scss'

const inter = Inter({
  subsets: ['latin'],
  // display: 'swap',
  adjustFontFallback: false,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

axios.interceptors.request.use(
  function (config) {
    // Do something before request is sent
    const auth = cookies().get(process.env.JWT_NAME!)
    console.log('read token as:', auth)
    return config
  },
  function (error) {
    // Do something with request error
    return Promise.reject(error)
  }
)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster
          position="top-center"
          gutter={12}
          containerStyle={{ margin: '8px' }}
          toastOptions={{
            success: {
              duration: 3000,
            },
            error: {
              duration: 5000,
            },
            style: {
              fontSize: '16px',
              maxWidth: 'max-content',
              padding: '16px 24px',
              color: '#333333',
            },
          }}
        />
        {children}
      </body>
    </html>
  )
}
